
PROGNAME=ianson
SRCS=ianson video_ctrl
CXFLAGS=
MORELIBS=sackcomm

LITERAL_LIBNAME2=video_mux_controller.isp
SRCS2=video_ctrl video_plugin
MORELIBS2=sackcomm


include $(ALTANIK_BASE)/makefiles/makefile.single
