
PROGNAME=msg.client.test
SRCS=service_client
MORELIBS=


ifdef __WINDOWS__
# also only for static compilation.
#ifdef __WINDOWS__
SYSLIBS=wsock32
endif

include $(SACK_BASE)/makefiles/makefile.single

