make MKCFLAGS=-D_OPENGL_DRIVER FINALDEST=/testgl COMPILER=wc DEST=debug DEST_PREFIX=gl- OPENGL=1 __WINDOWS__=1
make -C src/msgsvr/testdisplay MKCFLAGS=-D_OPENGL_DRIVER FINALDEST=/testgl COMPILER=wc DEST=debug DEST_PREFIX=gl- OPENGL=1 __WINDOWS__=1
