
APP_DEFAULT_DATA=$(foreach frame,$(shell ls frames),frames/$(frame))

PROJECTS=images

INCLUDEDIRS=..
LITERAL_LIBNAME=dekware.isp
SRCS=dekwarecon solitaire
MORELIBS=pscards
#MORE_LITERAL_LIBS=psicon.nex

include $(SACK_BASE)/makefiles/makefile.single
