
LIBNAME1=psi.console
SRCS1= psicon history WinLogic console_keydefs psicon_interface
CXFLAGS1=-DPSICON -DGRAPHCON -DCORE_CON -DCORECON_SOURCE -DPSI_CONSOLE_SOURCE -DPSI_SOURCE
SACK_LIBS1=



include $(SACK_BASE)/makefiles/makefile.many
