
CFLAGS=-ID:\bcc\include -ml -v -D_DEBUG

all: cpp.exe

OBJS = links.obj text.obj input.obj mem.obj cppmain.obj
cpp.exe: $(OBJS)
        tlink /Ld:\bcc\lib/c/s/m/l/v c0l.obj $(OBJS),cpp.exe,,cl mathl

links.obj: links.c

text.obj: text.c
        bcc -S $(CFLAGS) text.c
        tasm -ml text.asm

input.obj: input.c
        bcc $(CFLAGS) -c input.c

mem.obj: mem.c
        bcc $(CFLAGS) -c -B mem.c

cppmain.obj: cppmain.c
        bcc $(CFLAGS) -c cppmain.c



