PROGNAME1=shoimg
SUBSYSTEM1=windows
SRCS1=main


PROGNAME2=bounce_img
SUBSYSTEM2=windows
SRCS2=bounce

PROGNAME3=bounce_img2
SUBSYSTEM3=windows
SRCS3=bounce2

PROGNAME3=crossfade
SUBSYSTEM3=windows
SRCS3=crossfade

PROGNAME4=net_service_sign
SUBSYSTEM4=windows
SRCS4=netimage

PROGNAME5=net_service_announcer
SUBSYSTEM5=windows
SRCS5=netannounce
MORELIBS5=sack.widgets

include $(SACK_BASE)/makefiles/makefile.many
