ifndef SACK_BASE
all .DEFAULT:
	$(MAKE) -C .. $(MAKECMDGOALS)
else

MORE_PROJECTS=Makefile.widgets keypad/keypad/Makefile banner/banner_cmd/Makefile

include $(SACK_BASE)/makefiles/makefile.single

endif
