
APP_DEFAULT_DATA1=$(foreach frame,$(shell ls frames),frames/$(frame)) 


INCLUDEDIRS=..

LITERAL_LIBNAME9=tasks.isp
SRCS9=tasks
CXFLAGS9=-DSACK_CORE_BUILD
MORELIBS9=sack.widgets 

include $(SACK_BASE)/makefiles/makefile.many

