
function set-computer-name( [string]$name )
{
    $ComputerInfo = Get-WmiObject -Class Win32_ComputerSystem
    $ComputerInfo.rename($name).ReturnValue
}

set-computer-name $args[0]


# SIG # Begin signature block
# MIIEMwYJKoZIhvcNAQcCoIIEJDCCBCACAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUlr2WPTmysj/MZo2DngYV86iE
# txagggI9MIICOTCCAaagAwIBAgIQY84q6+WYEqNLa1yvxoLcNzAJBgUrDgMCHQUA
# MCwxKjAoBgNVBAMTIVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdDAe
# Fw0xMDA5MTQyMDQ5MTJaFw0zOTEyMzEyMzU5NTlaMBoxGDAWBgNVBAMTD1Bvd2Vy
# U2hlbGwgVXNlcjCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEArhrdcuBWTO9M
# m45bXgNKvJ/ip3aQsFSsFElTalLbc1418KBJfpCEm2i8t48t/zROr+LU2q3bZ7In
# 2dXhP3SgQQj/l1WpYpRGD2icbbmo6CJ3eSu3wLSkwQjDT7+77i63QxeMpw42QIEi
# O+ehTVjguIFpzG3VcjG9iiKjWMXyea0CAwEAAaN2MHQwEwYDVR0lBAwwCgYIKwYB
# BQUHAwMwXQYDVR0BBFYwVIAQjSYbR+XPair/dV+8lwIBEKEuMCwxKjAoBgNVBAMT
# IVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdIIQm+5pEZUyKbRFUtm3
# EA4HcTAJBgUrDgMCHQUAA4GBAAL/12Yk6yOrcy9LGscZfMTWsTh5EqcTyKMXZr9Q
# 2Sw21nJP8hyjg8aP+f9WgbiM8sN4shqz6yJS/hmqqarI2cFF9JoMRy7+MKxp3pqR
# rz8AyAdJJ65jZMHDxCr+8LbRoBM8xTWGUbQhC7tERWMAqin544Me/AOZ/aJ7jk+Z
# kbITMYIBYDCCAVwCAQEwQDAsMSowKAYDVQQDEyFQb3dlclNoZWxsIExvY2FsIENl
# cnRpZmljYXRlIFJvb3QCEGPOKuvlmBKjS2tcr8aC3DcwCQYFKw4DAhoFAKB4MBgG
# CisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcC
# AQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYE
# FP6IHnnxztrfFW5/9tUM326Wvu5bMA0GCSqGSIb3DQEBAQUABIGAjqEQagi03FYC
# hfNn14w9OMR/0EV/ojfOUOoFc+QtX0UPRguKyXCsQclML2jFPB63ghgTarrioShw
# i+ePT2K7wIIsPuBpoabukXVeDhdQqx5KCFxsw21JKdOVBlphcQmkaHDHL4n6/AU2
# EpIzhmEqgmBK+0cyc5elbYkyOEdZUaQ=
# SIG # End signature block
