
LINK_MINIMAL=1

APP_DEFAULT_DATA=frames/ConfigurePingStatusGraph.isframe

LITERAL_LIBNAME=network_monitor.isp
CXFLAGS=-DSACK_CORE_BUILD
# database setup
SRCS=global linegraph connect_stat packet_stat
# listbox controls
SRCS+=
# informational controls/variables
SRCS+=

INCLUDEDIRS=..

include $(SACK_BASE)/makefiles/makefile.single


