
PROGNAME1=scan_tdump
SRCS1=scan_tdump

PROGNAME2=scan_bin
SRCS2=scan_bin
MORELIBS2=
#SUBSYSTEM2=windows

#PROGNAME3=scan_prog
#SRCS3=scan_prog
#MORELIBS3=
#SUBSYSTEM3=windows

include $(ALTANIK_BASE)/makefiles/makefile.many
