#!/bin/bash

echo '- these settings should have already been set - FINALDEST, COMPILER!'
FINALDEST=~/work/testbed
COMPILER=lnx64


DEST_BASE_PATH=$(pwd)
SOURCE_PATH=$(pwd)/../../../../binglink
DESTINATION=$DEST_BASE_PATH/alpha2
PROGRAM_SOURCE=$(pwd)/..
#export PROGRAM_SOURCE
BINGLINK_BASE=~/work/binglink

cd $PROGRAM_SOURCE

if [[ ! -e $DESTINATION ]] ; then mkdir -p $DESTINATION; fi

cp $PROGRAM_SOURCE/milk $PROGRAM_SOURCE/vserver
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/msgsvr 				$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/bardservice 			$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/bardsend 				$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/bdata_control 			$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/alpha2server 			$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/video_event_relay 		$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/vserver $PROGRAM_SOURCE/milk.core\
	$PROGRAM_SOURCE/clock.isom \
        $PROGRAM_SOURCE/alpha2.isom \
        $PROGRAM_SOURCE/link_state.isom \
        $PROGRAM_SOURCE/legacy_interface.isom \
         $DESTINATION
         
cp $SOURCE_PATH/scripts/working/* $DESTINATION
mkdir $DESTINATION/fonts
cp $PROGRAM_SOURCE/fonts/* $DESTINATION/fonts
mkdir $DESTINATION/frames
cp $PROGRAM_SOURCE/frames/* $DESTINATION/frames
mkdir $DESTINATION/images
cp -R $PROGRAM_SOURCE/images/* $DESTINATION/images
cp -R $BINGLINK_BASE/../altanik/src/fut/widgets/ballrack/resources/images/rack $DESTINATION/images

$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/altanik.core 			$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/launchpad 			$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/launchcmd 			$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/bag.msg.core.service 		$DESTINATION
$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/*plugin 		$DESTINATION
#$PROGRAM_SOURCE/pcopy $PROGRAM_SOURCE/bag.display.plugin.static 	$DESTINATION

if [[ -d /root/bin ]]; then false;else mkdir /root/bin;fi

cp $BINGLINK_BASE/scripts/root/bin/* 		/root/bin

cp $BINGLINK_BASE/scripts/interface.conf        $DESTINATION
cp $BINGLINK_BASE/scripts/asound.state* 	$DEST_BASE_PATH
cp $BINGLINK_BASE/scripts/mkxinit 		$DESTINATION
cp $BINGLINK_BASE/bdtat_box_control/host.address.conf $DESTINATION
cp $BINGLINK_BASE/scripts/set_current_db 	$DESTINATION
cp $BINGLINK_BASE/scripts/etc/rc.d/mkfirewall.sh 	$DESTINATION
cp $BINGLINK_BASE/scripts/ianson 		$DESTINATION
cp $BINGLINK_BASE/scripts/blctrl 		$DESTINATION
cp $BINGLINK_BASE/scripts/videoctrl 		$DESTINATION
cp $BINGLINK_BASE/scripts/watchnetstat.new 	$DESTINATION
cp $BINGLINK_BASE/scripts/mark_ready2 		$DESTINATION/mark_ready2
cp $BINGLINK_BASE/scripts/sound_end_filter 	$DESTINATION
cp $BINGLINK_BASE/scripts/setdb  		$DESTINATION/setdb
cp $BINGLINK_BASE/scripts/sound_end_filter 	$DESTINATION
cp $BINGLINK_BASE/scripts/watch_task 		$DESTINATION

#cp $PROGRAM_SOURCE/bag.msg.core.service 	$DESTINATION
# no such thing?  if linked statically will reference this lib directly?
#cp $PROGRAM_SOURCE/altanik.core.static 		$DESTINATION

#statically linked project now has __NO_GUI__ flag set, so this is not available.
#cp $PROGRAM_SOURCE/bag.display.plugin.static 	$DESTINATION
#cp $PROGRAM_SOURCE/*.plugin                     $DESTINATION

if [[ ! -e $DESTINATION/sounds ]] ; then mkdir 			    $DESTINATION/sounds; fi
cp $BINGLINK_BASE/sounds/*  $DESTINATION/sounds

cd $DEST_BASE_PATH

rm dist.tgz
tar -czf dist.tgz *

#chmod 755 alpha2/mark_ready2 alpha2/watchnetstat.new alpha2/ianson alpha2/setdb mkxinit
#cp $BINGLINK_BASE/resources/*.ogg alpha2/sounds/. -fr --reply=yes
#cp $BINGLINK_BASE/binglink.milk.config alpha2
