#!/bin/bash
export PATH=$PATH:/usr/bin/X11
alsactl restore
nvida-settings -l -
xset -dpms
setterm -blank 0
xset s off
#cd ~/bingolink/fbi_replicator_backup
cd /usr/src/FortuNet/fbi-replicator-0.1
/usr/bin/xterm -geometry 80x20+1024+51 -e ./fbi-rep-server -p&
/usr/bin/xterm -geometry 80x20+1024+400 -e ./fbi-rep-gui& 
exec /usr/bin/xterm









