#!/bin/bash
scp $1 root@vsrvr.palacestation:/usr/src/FortuNet/$2
scp $1 root@vsrvr.texasstation:/usr/src/FortuNet/$2
scp $1 root@vsrvr.sunsetstation:/usr/src/FortuNet/$2
scp $1 root@vsrvr.boulderstation:/usr/src/FortuNet/$2
scp $1 root@vsrvr.santafestation:/usr/src/FortuNet/$2
scp $1 root@vsrvr.redrock:/usr/src/FortuNet/$2
