#!/bin/bash

SCRIPT_PATH=/usr/src/FortuNet/alpha2

address=$(ipof $1)

$SCRIPT_PATH/mkfirewall.sh $address $2

case $2 in
    $(hostname))
       DATABASE=$1
       ;;
    *)
       DATABASE=$1
       ;;
esac

echo "
[MySQL]
Description		= MySQL test database
#Trace		= Off
#TraceFile		= stderr
Driver		= MySQL
SERVER		= $DATABASE
USER		= fortunet
PASSWORD		= dkc408a1f
PORT		= 3306
DATABASE		= fortunet
" >/etc/odbc.ini
