#!/bin/bash

# Edit these variables as needed ###############################################
SERIAL_DEV=/dev/ttyUSB0
NUM_INPUTS=4
################################################################################

# DO NOT CHANGE ANY SETTINGS BELOW HERE!
SERIAL_SETUP_STR=500:5:cbd:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0

# Video switcher commands
CMD_DISPLAY_RESET=BD
CMD_DISPLAY_CAMERA=BC
CMD_DISPLAY_RESET_CAMERA='BD\rBC'
CMD_DISPLAY_PIP=BP
CMD_DISPLAY_PIP0=BP1

case "$1" in
    reset)
	echo -e "\r${CMD_DISPLAY_RESET}\r" >> $SERIAL_DEV
        ;;
    init)
        echo "Initializing video switch box"
        stty -F $SERIAL_DEV $SERIAL_SETUP_STR

        ;;
    display)
        if [ $2 -gt $NUM_INPUTS ]
        then
            echo "ERROR:  There are only ${NUM_INPUTS} camera feeds connected"
            exit 1
        else
            echo "Switching to camera ${2}"
            #echo -e "\r${CMD_DISPLAY_RESET}\r" >> $SERIAL_DEV
            echo -e "\r${CMD_DISPLAY_RESET_CAMERA}${2}\r" >> $SERIAL_DEV
        fi

        ;;
    pip)
        if [ -z "${2}" -o -z "${3}" ]
        then
            echo "ERROR:  ..."
            exit 1
        else
            echo "Displaying PIP (camera ${3} in camera ${2})"
            echo -e "\r${CMD_DISPLAY_RESET_CAMERA}${2}\r${CMD_DISPLAY_PIP}\r${CMD_DISPLAY_CAMERA}${3}\r" >> $SERIAL_DEV
            #echo -e "\r${CMD_DISPLAY_CAMERA}${2}\r" >> $SERIAL_DEV
            #echo -e "\r${CMD_DISPLAY_PIP}\r" >> $SERIAL_DEV
            #echo -e "\r${CMD_DISPLAY_CAMERA}${3}\r" >> $SERIAL_DEV
        fi

        ;;
    *)
        echo "USAGE:  ..."
esac
