#!/bin/bash

case $1 in
   server)
val=$(netstat -ant|grep 1234|awk '{print $6}')

echo $val waiting for vlc to be ready...
while [[ 1 ]]; do
	for i in $val; do
	  if [[ $i == "LISTEN" ]]; then
              exit
          fi;
        done
  	sleep 1;
  	echo -n .
  val=$(netstat -ant|grep 1234|awk '{print $6}')
done
   ;;
   client)
val=$(netstat -ant|grep 1234|awk '{print $6}')

echo $val waiting for vlc to be ready...
while [[ 1 ]]; do
	for i in $val; do
	  if [[ $i == "ESTABLISHED" ]]; then
              exit
          fi;
        done
  	sleep 1;
  	echo -n .
  val=$(netstat -ant|grep 1234|awk '{print $6}')
done
   ;;
esac
echo "done..."
