#!/bin/bash

echo '1)ace   Arizona Charlies East'
echo '2)acd   Arizona Charlies Decatur'
echo 'Please enter the number of the station this system is for'

read test
echo you entered $test
case $test in
	1)
        	NEW_HOST=ace
                NEW_HOSTNAME=vsrvr.ace
                ;;
	2)
        	NEW_HOST=acd
                NEW_HOSTNAME=vsrvr.acd
                ;;
esac

echo "NETWORKING=yes" >/etc/sysconfig/network
echo "HOSTNAME=$NEW_HOST" >>/etc/sysconfig/network
hostname $NEW_HOST
sed -i 's/IPADDR=.*/IPADDR='$(ipof $NEW_HOSTNAME)'/' /etc/sysconfig/network-scripts/ifcfg-eth0
cp /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/networking/devices
ifdown eth0
ifup eth0
case $test in 
	[1-4])
		/usr/src/FortuNet/alpha2/set_current_db vsrvr.ace ace
		;;
        [5-8])
        	/usr/src/FortuNet/alpha2/set_current_db vsrvr.acd acd
                ;;
esac

/usr/src/FortuNet/mkxinit DATABASE
exec bash
