
__NO_GUI__=1

LIBNAME1=lib3
SRCS1=lib3

LITERAL_LIBNAME2=lib2
SRCS2=lib2
MORELIBS2=lib3

LIBNAME3=lib1
SRCS3=lib1
MORE_LITERAL_LIBS3=lib2

PROGNAME4=main1
SRCS4=main
MORELIBS4=lib1


include ../../makefiles/makefile.many
