__NO_GUI__=1

LINK_MINIMAL=1
PROGNAME=launchcmd
SRCS=launchcmd
SUBSYSTEM=windows

PROGNAME2=launch_command
SRCS2=launchcmd
SUBSYSTEM2=console

include $(SACK_BASE)/makefiles/makefile.single

