
#APP_DEFAULT_DATA1=$(foreach frame,$(shell ls frames),frames/$(frame)) 


INCLUDEDIRS=..

LITERAL_LIBNAME9=calendar.isp
SRCS9=DateButton
#this needs to be set for make system... cmake should build against installed sack.
CXFLAGS9=-DSACK_CORE_BUILD

include $(SACK_BASE)/makefiles/makefile.many

