
LINK_MINIMAL=1

INCLUDEDIRS=../../..

APP_DEFAULT_DATA6=frames/ConfigureKeypad.isFrame frames/hotkey_change_property.isframe

LITERAL_LIBNAME6=keypad.isp
SRCS6=keypad
MORELIBS6=sack.widgets

include $(SACK_BASE)/makefiles/makefile.many

