
PROGNAME2=test_args_cmd
SRCS2=test_args_cmd

ifdef __WINDOWS__
PROGNAME3=test_args_win
SRCS3=test_args_win
endif

PROGNAME4=test_crit_sec
SRCS4=test_critsec

PROGNAME5=test_windows
SRCS5=test_windows

PROGNAME6=test_delete
SRCS6=test_delete

PROGNAME7=test_many_layered_windows
SRCS7=test_many_layered_windows
MORELIBS7=bag.video

PROGNAME8=test_binary_tree
SRCS8=test_binary_tree

PROGNAME9=test_coords
SRCS9=test_coords

PROGNAMEA=test_uuid
SRCSA=test_uuid
SYSLIBSA=rpcrt4

PROGNAMEA=test_genx_PI
SRCSA=test_genx_pi
SYSLIBSA=


include $(SACK_BASE)/makefiles/makefile.many
